# Generated by Django 3.2.7 on 2022-07-14 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create_by', models.CharField(max_length=128)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=128)),
                ('abb_name', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('cover', models.CharField(max_length=256)),
                ('order', models.IntegerField()),
                ('status', models.BinaryField()),
                ('password', models.CharField(max_length=64)),
                ('comments_num', models.IntegerField()),
                ('like_num', models.IntegerField()),
                ('allow_comment', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.category')),
                ('tags', models.ManyToManyField(blank=True, to='article.Tag')),
            ],
        ),
    ]
